vich_uploader:
    db_driver: orm

    mappings:
        category_images:
            uri_prefix: '%app.path.category_images%'
            upload_destination: '%kernel.root_dir%/../public/uploads/images/categories'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
