# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
parameters:
    app.path.category_images: /uploads/images/categories

easy_admin:
    entities:
        Category:
            class: App\AppBundle\Entity\Category
            controller: App\AppBundle\Controller\CategoryController
            list:
                max_results: 20
                fields:
                    - id
                    - title
                    - parent
                    - { property: 'image', type: 'image', base_path: '%app.path.category_images%' }
            form:
                fields:
                    - title
                    - description
                    - { property: 'imageFile', type: 'vich_image' }
                    - slug
                    - position
                    - tags
                    - parent
