parameters:
    locale: 'en'
    app.path.product_images: /uploads/images/products
    app.path.user_contracts: /uploads/files/user/contracts

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Repository,Tests}'

    app.cache_clear_listener:
            class: App\AppBundle\Listener\CacheClearListener
            tags:
                - { name: kernel.event_listener, event: easy_admin.post_update, method: onPostUpdate }
    app.hash_password_listener:
        class: App\AppBundle\Listener\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }
